import '../../features/container_tracking/domain/entities/container.dart';

/// Service for seeding sample data during development
class DataSeedingService {
  /// Generate sample containers for testing and demonstration
  static List<Container> generateSampleContainers() {
    final now = DateTime.now();

    return [
      Container(
        id: 'container_001',
        containerNumber: 'MSKU7654321',
        status: ContainerStatus.inTransit,
        currentLocation: const Location(
          name: 'Port of Los Angeles',
          address: '425 S Palos Verdes St',
          city: 'San Pedro',
          country: 'United States',
          latitude: 33.7424,
          longitude: -118.2631,
        ),
        destination: const Location(
          name: 'Port of Long Beach',
          address: '415 W Ocean Blvd',
          city: 'Long Beach',
          country: 'United States',
          latitude: 33.7701,
          longitude: -118.1937,
        ),
        origin: const Location(
          name: 'Shanghai Port',
          address: 'Pudong New Area',
          city: 'Shanghai',
          country: 'China',
          latitude: 31.2304,
          longitude: 121.4737,
        ),
        contents: 'Electronics and computer components',
        weight: 28500.0,
        priority: Priority.high,
        createdAt: now.subtract(const Duration(days: 10)),
        updatedAt: now.subtract(const Duration(hours: 2)),
        estimatedArrival: now.add(const Duration(days: 3)),
        notes: 'Handle with care - fragile electronics',
        trackingHistory: [
          TrackingEntry(
            id: 'track_001',
            containerId: 'container_001',
            status: ContainerStatus.loading,
            location: const Location(
              name: 'Shanghai Port',
              address: 'Pudong New Area',
              city: 'Shanghai',
              country: 'China',
              latitude: 31.2304,
              longitude: 121.4737,
            ),
            timestamp: now.subtract(const Duration(days: 10)),
            description: 'Container loaded at origin port',
          ),
          TrackingEntry(
            id: 'track_002',
            containerId: 'container_001',
            status: ContainerStatus.inTransit,
            location: const Location(
              name: 'Port of Los Angeles',
              address: '425 S Palos Verdes St',
              city: 'San Pedro',
              country: 'United States',
              latitude: 33.7424,
              longitude: -118.2631,
            ),
            timestamp: now.subtract(const Duration(hours: 2)),
            description: 'Arrived at US port, customs clearance in progress',
          ),
        ],
      ),

      Container(
        id: 'container_002',
        containerNumber: 'COSM9876543',
        status: ContainerStatus.delivered,
        currentLocation: const Location(
          name: 'Houston Distribution Center',
          address: '1234 Industrial Blvd',
          city: 'Houston',
          country: 'United States',
          latitude: 29.7604,
          longitude: -95.3698,
        ),
        destination: const Location(
          name: 'Houston Distribution Center',
          address: '1234 Industrial Blvd',
          city: 'Houston',
          country: 'United States',
          latitude: 29.7604,
          longitude: -95.3698,
        ),
        origin: const Location(
          name: 'Hamburg Port',
          address: 'Bei St. Annen 1',
          city: 'Hamburg',
          country: 'Germany',
          latitude: 53.5511,
          longitude: 9.9937,
        ),
        contents: 'Automotive parts and machinery',
        weight: 35200.0,
        priority: Priority.medium,
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now.subtract(const Duration(days: 1)),
        estimatedArrival: now.subtract(const Duration(days: 2)),
        actualArrival: now.subtract(const Duration(days: 1)),
        notes: 'Delivery completed successfully',
        trackingHistory: [
          TrackingEntry(
            id: 'track_003',
            containerId: 'container_002',
            status: ContainerStatus.delivered,
            location: const Location(
              name: 'Houston Distribution Center',
              address: '1234 Industrial Blvd',
              city: 'Houston',
              country: 'United States',
              latitude: 29.7604,
              longitude: -95.3698,
            ),
            timestamp: now.subtract(const Duration(days: 1)),
            description: 'Container delivered to final destination',
          ),
        ],
      ),

      Container(
        id: 'container_003',
        containerNumber: 'EVER1234567',
        status: ContainerStatus.delayed,
        currentLocation: const Location(
          name: 'Suez Canal',
          address: 'Suez Canal Authority',
          city: 'Ismailia',
          country: 'Egypt',
          latitude: 30.5965,
          longitude: 32.2715,
        ),
        destination: const Location(
          name: 'Port of Rotterdam',
          address: 'Wilhelminakade 909',
          city: 'Rotterdam',
          country: 'Netherlands',
          latitude: 51.9244,
          longitude: 4.4777,
        ),
        origin: const Location(
          name: 'Singapore Port',
          address: '1 Maritime Square',
          city: 'Singapore',
          country: 'Singapore',
          latitude: 1.2966,
          longitude: 103.8764,
        ),
        contents: 'Textiles and apparel',
        weight: 22100.0,
        priority: Priority.critical,
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(hours: 6)),
        estimatedArrival: now.add(const Duration(days: 7)),
        notes: 'Delayed due to heavy traffic in Suez Canal',
        trackingHistory: [
          TrackingEntry(
            id: 'track_004',
            containerId: 'container_003',
            status: ContainerStatus.delayed,
            location: const Location(
              name: 'Suez Canal',
              address: 'Suez Canal Authority',
              city: 'Ismailia',
              country: 'Egypt',
              latitude: 30.5965,
              longitude: 32.2715,
            ),
            timestamp: now.subtract(const Duration(hours: 6)),
            description:
                'Container delayed in Suez Canal due to traffic congestion',
          ),
        ],
      ),

      Container(
        id: 'container_004',
        containerNumber: 'HAPG5555666',
        status: ContainerStatus.loading,
        currentLocation: const Location(
          name: 'Port of Antwerp',
          address: 'Entrepotkaai 1',
          city: 'Antwerp',
          country: 'Belgium',
          latitude: 51.2194,
          longitude: 4.4025,
        ),
        destination: const Location(
          name: 'Port of New York',
          address: '1 Bay St',
          city: 'Staten Island',
          country: 'United States',
          latitude: 40.6176,
          longitude: -74.0707,
        ),
        origin: const Location(
          name: 'Port of Antwerp',
          address: 'Entrepotkaai 1',
          city: 'Antwerp',
          country: 'Belgium',
          latitude: 51.2194,
          longitude: 4.4025,
        ),
        contents: 'Chemical products and materials',
        weight: 31800.0,
        priority: Priority.low,
        createdAt: now.subtract(const Duration(hours: 12)),
        updatedAt: now.subtract(const Duration(minutes: 30)),
        estimatedArrival: now.add(const Duration(days: 12)),
        notes: 'Loading in progress, special handling required for chemicals',
        trackingHistory: [
          TrackingEntry(
            id: 'track_005',
            containerId: 'container_004',
            status: ContainerStatus.loading,
            location: const Location(
              name: 'Port of Antwerp',
              address: 'Entrepotkaai 1',
              city: 'Antwerp',
              country: 'Belgium',
              latitude: 51.2194,
              longitude: 4.4025,
            ),
            timestamp: now.subtract(const Duration(minutes: 30)),
            description: 'Container loading started at port terminal',
          ),
        ],
      ),

      Container(
        id: 'container_005',
        containerNumber: 'OOLU9988776',
        status: ContainerStatus.damaged,
        currentLocation: const Location(
          name: 'Miami Inspection Facility',
          address: '1455 NW 46th St',
          city: 'Miami',
          country: 'United States',
          latitude: 25.7617,
          longitude: -80.1918,
        ),
        destination: const Location(
          name: 'Atlanta Distribution Hub',
          address: '2500 Corporate Exchange Dr',
          city: 'Atlanta',
          country: 'United States',
          latitude: 33.7490,
          longitude: -84.3880,
        ),
        origin: const Location(
          name: 'Port of Santos',
          address: 'Av. Cândido Gaffrée, 680',
          city: 'Santos',
          country: 'Brazil',
          latitude: -23.9618,
          longitude: -46.3322,
        ),
        contents: 'Coffee beans and agricultural products',
        weight: 29400.0,
        priority: Priority.high,
        createdAt: now.subtract(const Duration(days: 8)),
        updatedAt: now.subtract(const Duration(hours: 4)),
        estimatedArrival: now.add(const Duration(days: 5)),
        notes:
            'Container damaged during transport, contents inspection required',
        trackingHistory: [
          TrackingEntry(
            id: 'track_006',
            containerId: 'container_005',
            status: ContainerStatus.damaged,
            location: const Location(
              name: 'Miami Inspection Facility',
              address: '1455 NW 46th St',
              city: 'Miami',
              country: 'United States',
              latitude: 25.7617,
              longitude: -80.1918,
            ),
            timestamp: now.subtract(const Duration(hours: 4)),
            description:
                'Damage detected during inspection, assessing contents',
          ),
        ],
      ),
    ];
  }
}
